#!/usr/bin/env python3
"""Generate docs/benchmarks/ from bench.json and remediate.json.

./scripts/bench_report.py bench.json docs/benchmarks [remediate.json]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

CHECKS = ["slow-queries", "seq-scans", "unused-indexes", "index-burden", "bloat", "blocking"]
ORDER = ["small", "realistic", "horror"]
LABEL = {"small": "Small", "realistic": "Realistic", "horror": "Horror"}
BLURB = {
    "small": "one app table",
    "realistic": "a decade of growth",
    "horror": "college project to startup to PE to offshore",
}


def size(n: int) -> str:
    if n >= 1024**3:
        return f"{n / 1024**3:.2f} GB"
    if n >= 1024**2:
        return f"{n / 1024**2:.0f} MB"
    return f"{n / 1024:.0f} kB"


def row(label: str, cells: list[str]) -> str:
    return f"| {label} | " + " | ".join(cells) + " |"


def write(path: Path, title: str, lines: list[str]) -> None:
    path.write_text(f"# {title}\n\n" + "\n".join(lines).rstrip() + "\n")


def main() -> int:
    data = json.loads(Path(sys.argv[1]).read_text())
    outdir = Path(sys.argv[2])
    outdir.mkdir(parents=True, exist_ok=True)
    rem_path = Path(sys.argv[3]) if len(sys.argv) > 3 else None

    by = {s["scenario"]: s for s in data["scenarios"]}
    runs = by["small"]["runs"]
    f = {s: by[s]["findings"] for s in ORDER}

    # ---------------------------------------------------------------- index
    idx = [
        f"Every check run **{runs} times** against three PostgreSQL 16 databases of "
        "escalating awfulness, plus a full remediation pass on each.",
        "",
        "| | Small | Realistic | Horror |",
        "|---|---|---|---|",
        row("", [BLURB[s] for s in ORDER]),
        row("Size", [size(by[s]["catalog"]["db_bytes"]) for s in ORDER]),
        row("Indexes", [f"{by[s]['catalog']['indexes']:,}" for s in ORDER]),
        row(
            "Unused",
            [
                f"{f[s]['unused_indexes']:,} "
                f"({100 * f[s]['unused_indexes'] / by[s]['catalog']['indexes']:.0f}%)"
                for s in ORDER
            ],
        ),
        row(
            "Slowest check",
            [f"{max(by[s]['query_ms'][c]['median'] for c in CHECKS):.1f} ms" for s in ORDER],
        ),
        "",
        "## Contents",
        "",
        "- [Scenarios](scenarios.md) — what the three databases contain",
        "- [Performance](performance.md) — query timings and how they scale",
        "- [Findings](findings.md) — the measurement that changed the tool",
        "- [Remediation](remediation.md) — what the write path actually did",
        "",
        "## Reproducing",
        "",
        "```bash",
        "./scripts/bench.py --runs 5 --out bench.json",
        "./scripts/bench_remediate.py --out remediate.json    # destructive",
        "./scripts/bench_report.py bench.json docs/benchmarks remediate.json",
        "```",
        "",
        "Scenario schemas are in [`scripts/scenarios/`](../../scripts/scenarios/).",
        "",
        "## Caveats",
        "",
        "- Warm cache, single host, PostgreSQL 16 in Docker with `fsync=off`. These measure "
        "the tool's scaling, not your storage.",
        "- `autovacuum=off` in every scenario, so bloat persists to be measured. Real servers "
        "reclaim continuously.",
        "- Diagnostic figures describe **plans**, not executed changes. Only "
        "[remediation](remediation.md) wrote anything.",
    ]
    write(outdir / "README.md", "Benchmarks", idx)

    # ------------------------------------------------------------ scenarios
    sc = [
        "Three PostgreSQL 16 databases, generated by "
        "[`scripts/scenarios/`](../../scripts/scenarios/).",
        "",
        "| | Small | Realistic | Horror |",
        "|---|---|---|---|",
        row("", [BLURB[s] for s in ORDER]),
        row("Size", [size(by[s]["catalog"]["db_bytes"]) for s in ORDER]),
        row("Tables", [f"{by[s]['catalog']['tables']:,}" for s in ORDER]),
        row("Indexes", [f"{by[s]['catalog']['indexes']:,}" for s in ORDER]),
        row("Heap", [size(by[s]["catalog"]["heap_bytes"]) for s in ORDER]),
        row("Index bytes", [size(by[s]["catalog"]["index_bytes"]) for s in ORDER]),
        row(
            "Index-to-heap",
            [
                f"**{100 * by[s]['catalog']['index_bytes'] / by[s]['catalog']['heap_bytes']:.0f}%**"
                for s in ORDER
            ],
        ),
        "",
        "## Small",
        "",
        "One `orders` table with the everyday problems: a few unused indexes covering each "
        "refusal category, dead tuples, and a sequential-scan hotspot. This is the shape most "
        "application databases are actually in.",
        "",
        "## Realistic",
        "",
        "Four whale tables, sixteen mid-size, and a long tail of 180 small ones — the "
        "distribution real databases have. Index hygiene that nobody revisited: redundant "
        "prefixes, an exact duplicate under a different name, unique indexes nobody queries.",
        "",
        "## Horror",
        "",
        "Ten years of decisions nobody was around to defend, in four strata:",
        "",
        "| Era | What it left behind |",
        "|---|---|",
        "| College project | Everything `text`, including dates and money. No constraints. "
        "Tables named `data`, `temp`, `test1`. |",
        "| Startup | Partitioning by copy-paste — a table per year. Indexes added during 3am "
        "outages, never removed. |",
        "| PE acquisition | Audit tables duplicating everything. Soft deletes, so nothing is "
        "ever really deleted. |",
        "| Offshore rewrite | An index on every column including four booleans. Backup tables. "
        "`users_final_v2_new`. |",
        "",
        'It also carries the identifiers that break naive tooling: `"Mixed.Case.Index"`, '
        '`"index\'with\'quotes"`, and a table named `"user data old"`.',
        "",
        f"Result: **{by['horror']['catalog']['indexes']:,} indexes across "
        f"{by['horror']['catalog']['tables']} tables**, "
        f"{100 * f['horror']['unused_indexes'] / by['horror']['catalog']['indexes']:.0f}% of "
        "them unread.",
    ]
    write(outdir / "scenarios.md", "Scenarios", sc)

    # ---------------------------------------------------------- performance
    idx_growth = by["horror"]["catalog"]["indexes"] / by["small"]["catalog"]["indexes"]
    worst = max(
        by["horror"]["query_ms"][c]["median"] / max(by["small"]["query_ms"][c]["median"], 0.01)
        for c in CHECKS
    )
    perf = [
        f"Median of {runs} runs, measured **in-process**. Milliseconds.",
        "",
        "| Check | Small | Realistic | Horror | Growth |",
        "|---|---|---|---|---|",
    ]
    for check in CHECKS:
        vals = [by[s]["query_ms"][check]["median"] for s in ORDER]
        factor = f"{vals[2] / vals[0]:.0f}x" if vals[0] > 0 else "—"
        perf.append(f"| `{check}` | {vals[0]:.1f} | {vals[1]:.1f} | {vals[2]:.1f} | {factor} |")
    perf += [
        "",
        "## Why these are measured in-process",
        "",
        f"**CLI startup costs {data['cli_startup_ms']:.0f} ms.** That is `uv run dbperf "
        "--version` — interpreter and import time before a single byte reaches PostgreSQL. "
        "It dominates end-to-end wall time at every scale.",
        "",
        "A first pass at this benchmark reported ~1s per check and was measuring Python's "
        "import time, not the tool. The numbers above are the queries.",
        "",
        "## Scaling",
        "",
        f"Catalog size grows **{idx_growth:.0f}x** from Small to Horror "
        f"({by['small']['catalog']['indexes']:,} to {by['horror']['catalog']['indexes']:,} "
        f"indexes). The heaviest check grows about **{worst:.0f}x** — sub-linear, because the "
        "statistics views are indexed and cost is dominated by `pg_relation_size()` calls per "
        "row returned.",
        "",
        "`slow-queries` and `blocking` are flat: both read a fixed-size working set regardless "
        "of how many tables exist.",
        "",
        "`free-space` is absent from this table because it reads table data rather than "
        "catalogs and is not comparable — it is also why it is excluded from `report`.",
    ]
    write(outdir / "performance.md", "Performance", perf)

    # ------------------------------------------------------------- findings
    ratio_real = f["realistic"]["droppable_bytes"] / max(f["realistic"]["under_floor_bytes"], 1)
    ratio_horror = f["horror"]["under_floor_bytes"] / max(f["horror"]["droppable_bytes"], 1)
    find = [
        "`drop-unused-indexes` applies an 8MB floor, borrowed from Ola Hallengren's "
        "`@MinNumberOfPages = 1000`. Running all three scenarios showed where that borrow "
        "breaks down.",
        "",
        "| | Small | Realistic | Horror |",
        "|---|---|---|---|",
        row(
            "Above floor — would drop",
            [f"{f[s]['droppable']} → **{size(f[s]['droppable_bytes'])}**" for s in ORDER],
        ),
        row(
            "Below floor — refused",
            [f"{f[s]['under_floor']:,} → {size(f[s]['under_floor_bytes'])}" for s in ORDER],
        ),
        "",
        f"On the realistic database the floor works exactly as intended: what it surfaces "
        f"holds {ratio_real:.1f}x more than everything it dismisses.",
        "",
        f"**On the horror database it inverts.** The {f['horror']['under_floor']:,} indexes "
        f"dismissed as too small to bother with hold {ratio_horror:.1f}x *more* than the "
        f"{f['horror']['droppable']} it would act on.",
        "",
        "## Bytes were the lesser cost",
        "",
        "| | Small | Realistic | Horror |",
        "|---|---|---|---|",
        row("Worst table", [f"`{f[s]['worst_table']}`" for s in ORDER]),
        row("Unused / total indexes", [f"{f[s]['worst_unused']}" for s in ORDER]),
        row("Redundant index writes", [f"{f[s]['redundant_writes']:,}" for s in ORDER]),
        "",
        f"`{f['horror']['worst_table']}` carries {f['horror']['worst_unused']} indexes unread. "
        "Every `INSERT` pays that many B-tree writes serving no query, whether those indexes "
        "are 16kB or 16MB. A per-index size floor is structurally unable to see it.",
        "",
        "That is what `index-burden` exists for: it ranks tables by "
        "`unused indexes × row modifications` rather than by size. The floor was a sound "
        "borrow for *maintenance* — rebuilding a tiny index really is pointless — and the "
        "wrong instrument for *dropping*.",
        "",
        "## The second blind spot",
        "",
        "`bloat` counts dead tuples. After a vacuum those read zero while the file stays "
        "exactly as large, because plain `VACUUM` marks space reusable rather than returning "
        "it to the OS.",
        "",
        "Measured on the horror database **after** the remediation pass:",
        "",
        "| Check | Result |",
        "|---|---|",
        "| `bloat` | **0 tables** |",
        "| `free-space` | **31 tables, 1.03 GB reclaimable** |",
        "| Dead tuples on those tables | **0%** |",
        "",
        "`free-space` was added to close this. It uses `pgstattuple`, or "
        "`pgstattuple_approx` above a size threshold, and reports which was used.",
    ]
    write(outdir / "findings.md", "Findings", find)

    # ---------------------------------------------------------- remediation
    if rem_path and rem_path.exists():
        rem = {r["scenario"]: r for r in json.loads(rem_path.read_text())}
        heaps = ", ".join(
            f"{LABEL[s]} {size(rem[s]['before']['heap_bytes'])} → "
            f"{size(rem[s]['after_vacuum']['heap_bytes'])}"
            for s in ORDER
        )
        cw = rem["horror"].get("concurrent_writes") or {}
        rm = [
            "`vacuum --execute` then `drop-unused-indexes --execute`, against the same three "
            "databases. Wall times include ~1s of CLI startup.",
            "",
            "| | Small | Realistic | Horror |",
            "|---|---|---|---|",
            row("Dead tuples before", [f"{rem[s]['before']['dead_tuples']:,}" for s in ORDER]),
            row("Dead tuples after", [f"**{rem[s]['after']['dead_tuples']:,}**" for s in ORDER]),
            row("VACUUM time", [f"{rem[s]['vacuum_seconds']:.1f}s" for s in ORDER]),
            row("Indexes dropped", [f"{rem[s]['dropped']}" for s in ORDER]),
            row(
                "Index bytes",
                [
                    f"{size(rem[s]['before']['index_bytes'])} → "
                    f"**{size(rem[s]['after']['index_bytes'])}**"
                    for s in ORDER
                ],
            ),
            row(
                "Database size",
                [
                    f"{size(rem[s]['before']['db_bytes'])} → "
                    f"**{size(rem[s]['after']['db_bytes'])}**"
                    for s in ORDER
                ],
            ),
            row(
                "Restore",
                [
                    f"{rem[s]['restore']['seconds']:.1f}s ({rem[s]['restore']['statements']} stmts)"
                    if rem[s]["restore"]
                    else "—"
                    for s in ORDER
                ],
            ),
            "",
            "## VACUUM does not shrink the file",
            "",
            f"Every dead tuple was reclaimed — {rem['horror']['before']['dead_tuples']:,} on "
            f"Horror alone — and heap size did not move: {heaps}.",
            "",
            "That is correct behaviour, not a failure. Plain `VACUUM` marks space reusable by "
            "future inserts; it does not return it to the operating system. Only `VACUUM FULL` "
            "does, and it rewrites the table under an `ACCESS EXCLUSIVE` lock — an outage on "
            "anything large.",
            "",
            "**Every byte of on-disk reduction above came from dropping indexes, none from "
            "vacuuming.**",
            "",
            "## CONCURRENTLY, verified under load",
            "",
            f"A second connection inserted continuously while {rem['horror']['dropped']} "
            f"indexes were dropped from the Horror database. It committed "
            f"**{cw.get('commits', 0):,} rows** with a worst-case stall of "
            f"**{cw.get('max_stall_ms', 0)} ms** and {len(cw.get('errors', []))} errors.",
            "",
            "`DROP INDEX CONCURRENTLY` takes a `SHARE UPDATE EXCLUSIVE` lock rather than an "
            "`ACCESS EXCLUSIVE` one, so writes keep flowing. Worth measuring rather than "
            "repeating from the manual — it is the difference between a maintenance window "
            "and an incident.",
            "",
            "## Round trip",
            "",
            "Each drop was restored from its manifest alone. On Horror that included "
            '`"Mixed.Case.Index"`, `"index\'with\'quotes"` and an index on a table named '
            '`"user data old"` — all recreated exactly, which is what the `sql.Identifier` '
            "quoting is for.",
        ]
        write(outdir / "remediation.md", "Remediation", rm)

    print(f"wrote {outdir}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
